# ================================
# SERVER
# ================================
server.port=8082

# ================================
# PostgreSQL DATABASE
# ================================
spring.datasource.url=jdbc:postgresql://postgres-reports:5432/reportsdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================
# MAIL (Gmail)
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=test@gmail.com
spring.mail.password=test
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================================
# Eureka
# ================================
spring.application.name=REPORTING-SERVICE
eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true

# ================================
# LOGS
# ================================
logging.level.tn.esprit.ms_reporting=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
